class AddIndexesToOrganizations < ActiveRecord::Migration
  def self.up
    add_index(:organizations, :master_type)
    add_index(:organizations, :owner_id)
    add_index(:organizations, :selected_plan)
    add_index(:organizations, :logo_file_name)
    add_index(:organizations, :url)
    add_index(:organizations, :is_student_friendly)
    add_index(:organizations, :is_motorcoach_friendly)
    add_index(:organizations, :acronym)
    add_index(:organizations, :keywords)
    add_index(:roles, :title)
    add_index(:roles, :organization_id)
    add_index(:roles, :is_organization_approved)
    add_index(:roles, :is_user_approved)
    add_index(:roles, :is_admin)
    add_index(:contact_methods, :name)
    add_index(:users, :name_first)
    add_index(:users, :name_last)
    add_index(:users, :avatar_file_name)
    add_index(:users, :is_travel_planner)
    add_index(:ratings, :stars)
    add_index(:ratings, :is_open)
    add_index(:ratings, :is_closed)
  end

  def self.down
    remove_index(:organizations, :master_type)
    remove_index(:organizations, :owner_id)
    remove_index(:organizations, :selected_plan)
    remove_index(:organizations, :logo_file_name)
    remove_index(:organizations, :url)
    remove_index(:organizations, :is_student_friendly)
    remove_index(:organizations, :is_motorcoach_friendly)
    remove_index(:organizations, :acronym)
    remove_index(:organizations, :keywords)
    remove_index(:roles, :title)
    remove_index(:roles, :organization_id)
    remove_index(:roles, :is_organization_approved)
    remove_index(:roles, :is_user_approved)
    remove_index(:roles, :is_admin)
    remove_index(:contact_methods, :name)
    remove_index(:users, :name_first)
    remove_index(:users, :name_last)
    remove_index(:users, :avatar_file_name)
    remove_index(:users, :is_travel_planner)
    remove_index(:ratings, :stars)
    remove_index(:ratings, :is_open)
    remove_index(:ratings, :is_closed)
  end
end
